---
openapi: "3.0.3"
info:
  title: "cm.domeni.authentis-users"
  description: "Demo use open APi for generate REST API endpoints"
  version: "0.0.1"
servers:
- url: "https"
- url: "http"
paths:
  /demo:
    get:
      tags:
      - "Demo"
      summary: "Demo Summary"
      description: "Demo Description"
      operationId: "fetchAllDemo"
      security:
      - bearerAuth: []
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DemoDTO"
        "401":
          description: "Unauthorized"
    post:
      tags:
      - "Demo"
      summary: "Create a new Demo"
      description: "Creates a new Demo with the provided data"
      operationId: "createDemo"
      security:
      - bearerAuth: []
      requestBody:
        description: "Demo object to be created"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DemoDTO"
      responses:
        "201":
          description: "Demo created successfully"
          content:
            application/json:
              schema:
                type: "string"
                format: "uuid"
        "400":
          description: "Invalid input"
        "401":
          description: "Unauthorized"
  /register:
    post:
      tags:
      - "User"
      summary: "register user"
      description: "register user"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        "201":
          description: "User created successfully"
          content:
            application/json:
              schema:
                type: "string"
                format: "uuid"
        "400":
          description: "Bad request"
        "409":
          description: "this username already exist"
  /user:
    get:
      tags:
      - "User"
      summary: "get user info"
      description: "get user info including id, username, and all roles"
      operationId: "fetchAllUsers"
      security:
      - bearerAuth: []
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserDTO"
        "401":
          description: "Unauthorized"
        "404":
          description: "User not found"
  /role:
    post:
      tags:
      - "Role"
      summary: "create new role"
      description: "create role"
      operationId: "createRole"
      security:
      - oAuth:
        - "role:create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRoleDTO"
      responses:
        "201":
          description: "Role created successfully"
          content:
            application/json:
              schema:
                type: "string"
                format: "uuid"
        "409":
          description: "this role already exist"
  /users/{userId}/roles/{roleName}:
    put:
      tags:
      - "User"
      operationId: "addRoleToUser"
      summary: "Add roles to a user"
      parameters:
      - in: "path"
        name: "userId"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "The user ID"
      - in: "path"
        name: "roleName"
        required: true
        schema:
          type: "string"
        description: "The name of the role to be added"
      security:
      - oAuth:
        - "role:assign"
      responses:
        "204":
          description: "Roles added successfully"
        "404":
          description: "User/role not found"
        "400":
          description: "Invalid role name"
    delete:
      tags:
      - "User"
      summary: "Remove roles to a user"
      description: "Remove roles  to a user"
      operationId: "removeRoleToUser"
      parameters:
      - in: "path"
        name: "userId"
        required: true
        schema:
          type: "string"
          format: "uuid"
      - in: "path"
        name: "roleName"
        required: true
        schema:
          type: "string"
          description: "The name of the role to be removed"
      security:
      - oAuth:
        - "role:delete"
      responses:
        "204":
          description: "Roles removed successfully"
        "404":
          description: "User/role not found"
        "400":
          description: "Invalid role name"
components:
  schemas:
    DemoDTO:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
    UserDTO:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        userName:
          type: "string"
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          writeOnly: true
        firstName:
          type: "string"
        lastName:
          type: "string"
        birthDate:
          type: "string"
          format: "date"
        address:
          $ref: "#/components/schemas/AddressDTO"
    AddressDTO:
      properties:
        city:
          type: "string"
          description: "city of address"
    CreateUser:
      required:
      - "userName"
      - "email"
      - "password"
      type: "object"
      properties:
        userName:
          type: "string"
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          writeOnly: true
        firstName:
          type: "string"
        lastName:
          type: "string"
        birthDate:
          type: "string"
          format: "date"
        address:
          $ref: "#/components/schemas/AddressDTO"
    CreateRoleDTO:
      required:
      - "name"
      properties:
        name:
          type: "string"
          description: "name of role"
        description:
          type: "string"
          description: "description of role"
