services:
  postgres_authenthis_users:
    image: postgres:17
    container_name: authentis-postgres_authenthis_users-db
    environment:
      POSTGRES_DB: authentis-users-db
      POSTGRES_USER: domeni.ngameni
      POSTGRES_PASSWORD: authentis-users-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_authenthis_users:/var/lib/postgresql/data
    networks:
      microservices_network:
        aliases:
          - postgres_authenthis_users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U domeni.ngameni -d authentis-users-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_keycloak:
    image: postgres:17
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: domeni.ngameni
      POSTGRES_DB: keycloak_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      microservices_network:
        aliases:
          - postgres_keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_image:
    image: postgres:17
    container_name: authetis_user_postgres_image
    environment:
      POSTGRES_USER: domeni.ngameni
      POSTGRES_PASSWORD: authentis-users-password
      POSTGRES_DB: authentis-users-db
    ports:
      - "5436:5432"
    volumes:
      - postgres_image_data:/var/lib/postgresql/data
    networks:
      microservices_network:
        aliases:
          - postgres_image
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U domeni.ngameni -d authentis-users-db"]
      interval: 30s
      timeout: 10s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentis-users-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: domeni.ngameni
      KC_BOOTSTRAP_ADMIN_PASSWORD: authentis-users-password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: domeni.ngameni
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_ENV: production
      KC_HOSTNAME_STRICT: "false"
      LOG_LEVEL: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - microservices_network
    command: start

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: domeni.ngameni@authentisuser.cm
      PGADMIN_DEFAULT_PASSWORD: domeni.ngameni
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices_network
    restart: unless-stopped
    depends_on:
      - postgres_authenthis_users
      - postgres_image
      - postgres_keycloak
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/misc/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_authenthis_users:
    driver: local
  postgres_keycloak_data:
    driver: local
  pgadmin_data:
    driver: local
  postgres_image_data:
    driver: local

networks:
  microservices_network:
    driver: bridge